### Create comment on parent comment
POST http://localhost:3000/api/comments/5
Content-Type: application/x-www-form-urlencoded

content=So cool!

### Upvote comment
PATCH http://localhost:3000/api/comments/7/upvote