### Create post
POST http://localhost:3000/api/posts
Content-Type: application/x-www-form-urlencoded

title="We can now fix McDonald's ice cream machines"
&url=https://www.ifixit.com/News/102368/victory-is-sweet-we-can-now-fix-mcdonalds-ice-cream-machines

### Create post comment
POST http://localhost:3000/api/posts/3/comment
Content-Type: application/x-www-form-urlencoded

content=Found it on Twitter!

### Get all posts
GET http://localhost:3000/api/posts

### Get all post comments
GET http://localhost:3000/api/posts/3/comments

### Get post by id
GET http://localhost:3000/api/posts/3

### Upvote post
PATCH http://localhost:3000/api/posts/3/upvote