### Create post
POST http://localhost:3000/api/posts
Content-Type: application/x-www-form-urlencoded

title=Super cool tutorial
&url=https://www.youtube.com/watch?v=eHbO5OWBBpg

### Create post comment
POST http://localhost:3000/api/posts/5/comment
Content-Type: application/x-www-form-urlencoded

content=It's by Better Stack!

### Get all posts
GET http://localhost:3000/api/posts

### Get all post comments
GET http://localhost:3000/api/posts/5/comments?includeChildren=true

### Get post by id
GET http://localhost:3000/api/posts/5

### Upvote post
PATCH http://localhost:3000/api/posts/5/upvote